[package]
name = "random"
version = "0.1.0"
authors = ["Ahmad Kabani <ahmadkabani@yahoo.com>"]
edition = "2024"

[dependencies]
rand = { workspace = true }
rand_chacha = { workspace = true }
glam = { workspace = true }
